openapi: 3.0.3
info:
  title: Ang API
  version: 0.0.0
  description: Demo project
paths:
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /country/:
    get:
      operationId: country_retrieve
      tags:
      - country
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
          description: ''
  /country_cities/:
    get:
      operationId: country_cities_retrieve
      tags:
      - country_cities
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
          description: ''
  /policy/:
    get:
      operationId: policy_retrieve
      tags:
      - policy
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Politics'
          description: ''
components:
  schemas:
    Continents:
      type: object
      properties:
        pk:
          type: string
          readOnly: true
        country:
          type: string
          maxLength: 4
        continent:
          type: string
          maxLength: 20
        percentage:
          type: number
          format: double
          nullable: true
      required:
      - continent
      - country
      - pk
    Country:
      type: object
      properties:
        code:
          type: string
          maxLength: 4
        politics:
          $ref: '#/components/schemas/Politics'
        continents:
          $ref: '#/components/schemas/Continents'
        economy:
          $ref: '#/components/schemas/Economy'
        name:
          type: string
          maxLength: 35
        capital:
          type: string
          nullable: true
          maxLength: 35
        province:
          type: string
          nullable: true
          maxLength: 35
        area:
          type: number
          format: double
          nullable: true
        population:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          nullable: true
      required:
      - code
      - continents
      - economy
      - name
      - politics
    Economy:
      type: object
      properties:
        country:
          type: string
          maxLength: 4
        gdp:
          type: number
          format: double
          nullable: true
        agriculture:
          type: number
          format: double
          nullable: true
        service:
          type: number
          format: double
          nullable: true
        industry:
          type: number
          format: double
          nullable: true
        inflation:
          type: number
          format: double
          nullable: true
      required:
      - country
    Politics:
      type: object
      properties:
        country:
          type: string
          maxLength: 4
        independence:
          type: string
          format: date
          nullable: true
        dependent:
          type: string
          nullable: true
          maxLength: 4
        government:
          type: string
          nullable: true
          maxLength: 120
      required:
      - country
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
