/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Continents } from './models/continents';
export type { Country } from './models/country';
export type { Economy } from './models/economy';
export type { Politics } from './models/politics';
