/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Continents {
  continent: string;
  country: string;
  percentage?: number | null;
  pk: string;
}
