/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Country {
  area?: number | null;
  capital?: string | null;
  code: string;
  name: string;
  population?: number | null;
  province?: string | null;
}
