/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Continents } from '../models/continents';
import { Economy } from '../models/economy';
import { Politics } from '../models/politics';
export interface Country {
  area?: number | null;
  capital?: string | null;
  code: string;
  continents: Continents;
  economy: Economy;
  name: string;
  politics: Politics;
  population?: number | null;
  province?: string | null;
}
