/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Economy {
  agriculture?: number | null;
  country: string;
  gdp?: number | null;
  industry?: number | null;
  inflation?: number | null;
  service?: number | null;
}
