/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Politics {
  country: string;
  dependent?: string | null;
  government?: string | null;
  independence?: string | null;
}
