/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiSchemaRetrieve$Json } from '../fn/api/api-schema-retrieve-json';
import { ApiSchemaRetrieve$Json$Params } from '../fn/api/api-schema-retrieve-json';
import { apiSchemaRetrieve$VndOaiOpenapi } from '../fn/api/api-schema-retrieve-vnd-oai-openapi';
import { ApiSchemaRetrieve$VndOaiOpenapi$Params } from '../fn/api/api-schema-retrieve-vnd-oai-openapi';
import { apiSchemaRetrieve$Yaml } from '../fn/api/api-schema-retrieve-yaml';
import { ApiSchemaRetrieve$Yaml$Params } from '../fn/api/api-schema-retrieve-yaml';

@Injectable({ providedIn: 'root' })
export class ApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiSchemaRetrieve()` */
  static readonly ApiSchemaRetrievePath = '/api/schema/';

  /**
   * OpenApi3 schema for this API. Format can be selected via content negotiation.
   *
   * - YAML: application/vnd.oai.openapi
   * - JSON: application/vnd.oai.openapi+json
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSchemaRetrieve$VndOaiOpenapi()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSchemaRetrieve$VndOaiOpenapi$Response(params?: ApiSchemaRetrieve$VndOaiOpenapi$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: any;
}>> {
    return apiSchemaRetrieve$VndOaiOpenapi(this.http, this.rootUrl, params, context);
  }

  /**
   * OpenApi3 schema for this API. Format can be selected via content negotiation.
   *
   * - YAML: application/vnd.oai.openapi
   * - JSON: application/vnd.oai.openapi+json
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSchemaRetrieve$VndOaiOpenapi$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSchemaRetrieve$VndOaiOpenapi(params?: ApiSchemaRetrieve$VndOaiOpenapi$Params, context?: HttpContext): Observable<{
[key: string]: any;
}> {
    return this.apiSchemaRetrieve$VndOaiOpenapi$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: any;
}>): {
[key: string]: any;
} => r.body)
    );
  }

  /**
   * OpenApi3 schema for this API. Format can be selected via content negotiation.
   *
   * - YAML: application/vnd.oai.openapi
   * - JSON: application/vnd.oai.openapi+json
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSchemaRetrieve$Yaml()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSchemaRetrieve$Yaml$Response(params?: ApiSchemaRetrieve$Yaml$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: any;
}>> {
    return apiSchemaRetrieve$Yaml(this.http, this.rootUrl, params, context);
  }

  /**
   * OpenApi3 schema for this API. Format can be selected via content negotiation.
   *
   * - YAML: application/vnd.oai.openapi
   * - JSON: application/vnd.oai.openapi+json
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSchemaRetrieve$Yaml$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSchemaRetrieve$Yaml(params?: ApiSchemaRetrieve$Yaml$Params, context?: HttpContext): Observable<{
[key: string]: any;
}> {
    return this.apiSchemaRetrieve$Yaml$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: any;
}>): {
[key: string]: any;
} => r.body)
    );
  }

  /**
   * OpenApi3 schema for this API. Format can be selected via content negotiation.
   *
   * - YAML: application/vnd.oai.openapi
   * - JSON: application/vnd.oai.openapi+json
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSchemaRetrieve$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSchemaRetrieve$Json$Response(params?: ApiSchemaRetrieve$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: any;
}>> {
    return apiSchemaRetrieve$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * OpenApi3 schema for this API. Format can be selected via content negotiation.
   *
   * - YAML: application/vnd.oai.openapi
   * - JSON: application/vnd.oai.openapi+json
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSchemaRetrieve$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSchemaRetrieve$Json(params?: ApiSchemaRetrieve$Json$Params, context?: HttpContext): Observable<{
[key: string]: any;
}> {
    return this.apiSchemaRetrieve$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: any;
}>): {
[key: string]: any;
} => r.body)
    );
  }

}
